### ISSUE TITLE
I get this error, and the pfg doesn't effect the output

### ISSUE THREAD

**Issue by ahakagei** [laksjdjf/pfg-webui#2]
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 10240 for tensor number 1 in the list.

**Comment by ahakagei** [comment]
Here is the full thing

File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

  5%|████▏                                                                              | 1/20 [00:01<00:33,  1.77s/it]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 10%|████████▎                                                                          | 2/20 [00:01<00:14,  1.23it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 15%|████████████▍                                                                      | 3/20 [00:02<00:08,  1.99it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 20%|████████████████▌                                                                  | 4/20 [00:02<00:05,  2.79it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 25%|████████████████████▊                                                              | 5/20 [00:02<00:04,  3.60it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 30%|████████████████████████▉                                                          | 6/20 [00:02<00:03,  4.35it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 35%|█████████████████████████████                                                      | 7/20 [00:02<00:02,  5.02it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 40%|█████████████████████████████████▏                                                 | 8/20 [00:02<00:02,  5.58it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 45%|█████████████████████████████████████▎                                             | 9/20 [00:02<00:01,  6.03it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 50%|█████████████████████████████████████████                                         | 10/20 [00:03<00:01,  6.36it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 55%|█████████████████████████████████████████████                                     | 11/20 [00:03<00:01,  6.64it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 60%|█████████████████████████████████████████████████▏                                | 12/20 [00:03<00:01,  6.85it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 65%|█████████████████████████████████████████████████████▎                            | 13/20 [00:03<00:01,  7.00it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 70%|█████████████████████████████████████████████████████████▍                        | 14/20 [00:03<00:00,  7.11it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 75%|█████████████████████████████████████████████████████████████▌                    | 15/20 [00:03<00:00,  7.17it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 80%|█████████████████████████████████████████████████████████████████▌                | 16/20 [00:03<00:00,  7.21it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 85%|█████████████████████████████████████████████████████████████████████▋            | 17/20 [00:03<00:00,  7.21it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 90%|█████████████████████████████████████████████████████████████████████████▊        | 18/20 [00:04<00:00,  7.24it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

 95%|█████████████████████████████████████████████████████████████████████████████▉    | 19/20 [00:04<00:00,  7.27it/s]Error executing callback cfg_denoiser_callback for E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py
Traceback (most recent call last):
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "E:\Stabilized-Diffusion automatic1111\Stable-diffusion-automatic1111\extensions\pfg-webui\scripts\pfg-webui.py", line 91, in denoiser_callback
    params.text_cond = torch.cat([cond,pfg_cond],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 768 but got size 2048 for tensor number 1 in the list.

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.58it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.88it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  7.34it/s]

**Comment by laksjdjf** [comment]
Sorry, my model only supports v2.

**Comment by laksjdjf** [comment]
Unfortunately, my model only supports v2.

**Comment by surfishs** [comment]
> 

I don't understand what you mean. I have also encountered the same problem. How should I fix it?

**Comment by surfishs** [comment]
@laksjdjf

**Comment by laksjdjf** [comment]
> > 
> 
> I don't understand what you mean. I have also encountered the same problem. How should I fix it?

If you want to use a model trained from SD1.x , please use [pfg-novel-n10.pt](https://huggingface.co/furusu/PFG/blob/main/pfg-novel-n10.pt). For SD2.x, please use [pfg-wd15beta2-n10.pt](https://huggingface.co/furusu/PFG/blob/main/pfg-wd15beta2-n10.pt). Please keep the num tokens setting at the default of 10.
